### ISSUE TITLE
Webpack frontend build failing with docker-compose up --build

### ISSUE THREAD

**Issue by selipso** [briancappello/flask-react-spa#1]
Thanks for this comprehensive build stack with Flask. The frontend build seems to be failing for me on Ubuntu 18.04 with docker. Tried to use it with docker-compose and received the following error in the logs when building with `docker-compose up --build`:

```
> frontend@0.0.1 build:dll /flask
> node frontend/internals/scripts/dependencies.js

Building the Webpack DLL...
module.js:529
throw err;
^

Error: Cannot find module '/flask/frontend/app/config'
at Function.Module._resolveFilename (module.js:527:15)
at Function.Module._load (module.js:476:23)
at Module.require (module.js:568:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/flask/frontend/internals/webpack/webpack.base.config.js:5:19)
at Module._compile (module.js:624:30)
at Object.Module._extensions..js (module.js:635:10)
at Module.load (module.js:545:32)
at tryModuleLoad (module.js:508:12)
at Function.Module._load (module.js:500:3)
npm info lifecycle frontend@0.0.1~postbuild:dll: frontend@0.0.1
npm info ok 
```

**Comment by selipso** [comment]
Actually, I missed a couple steps in the documentation related to the config. Closing this for now.

Edit: Still getting the build failure. After launching a new instance of docker-compose, the frontend container is not up.

**Comment by briancappello** [comment]
Hey, thanks for the report! I think it may have been an order-of-operations bug where it would error-out if the config file was missing, and then not recover correctly on the second run. I pushed a commit to master that hopefully might fix your problem. Can you please give it a shot and let me know? Thanks!

**Comment by selipso** [comment]
@briancappello Looks great! Thanks for the quick fix. Awesome plug-and-play nature with docker-compose.
