### ISSUE TITLE
Celery Error

### ISSUE THREAD

**Issue by hansfordj** [briancappello/flask-react-spa#3]
Getting this error both via docker install and local install (Ubuntu 18.04):

celery_worker_1  | [2018-08-18 19:53:28,411: INFO/MainProcess] Received task: backend.tasks.send_mail_async_task[836cae7a-f34c-420e-adf0-d4c569891732]
celery_worker_1  | [2018-08-18 19:53:28,426: ERROR/ForkPoolWorker-1] Task backend.tasks.send_mail_async_task[836cae7a-f34c-420e-adf0-d4c569891732] raised unexpected: AttributeError("'FlaskCelery' object has no attribute 'app'",)
celery_worker_1  | Traceback (most recent call last):
celery_worker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
celery_worker_1  |     R = retval = fun(*args, **kwargs)
celery_worker_1  |   File "/flask/src/backend/extensions/celery.py", line 24, in __call__
celery_worker_1  |     with _celery.app.app_context():
celery_worker_1  | AttributeError: 'FlaskCelery' object has no attribute 'app'

**Comment by briancappello** [comment]
Hi, thanks for the report!

I pushed [this commit](https://github.com/briancappello/flask-react-spa/commit/256be0e27c217a1d09425d4cfbbfbd18875b8aef) that should hopefully fix this issue.

Can you let me know if it works? (or just close the issue if it does)
Thanks!

**Comment by hansfordj** [comment]
Woah, thanks for quick response!
I will test later tonight/tomorrow when I'm back home and hopefully close this.
Cheers!

**Comment by hansfordj** [comment]
Getting either  Network is unreachable or Timeout errors using gmail or zoho settings. However, the original error is fixed, so I will close this and try to fix my mail server tomorrow. Thanks for the help.

**Comment by briancappello** [comment]
If you mean in production, could be the firewall needs a port opened? Def check the ssl and tls settings too

**Comment by hansfordj** [comment]
Didn't have mailhog installed when testing last night. Also, my first time using Google Compute Engine rather than Digital Ocean, so it was likely a firewall issue. Working as expected in development through Docker/mailhog now. Thanks for the fix, learning a lot from this project!
